In [1]:
import numpy as np
from scipy.stats import binom

In [2]:
k = np.array([i for i in range(13)])
n_k = np.array([3, 24, 104, 286, 670, 1033, 1343, 1112, 829, 478, 181, 45, 7])
display(k)
n_k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([   3,   24,  104,  286,  670, 1033, 1343, 1112,  829,  478,  181,
         45,    7])

In [3]:
n = len(k) - 1
N = np.sum(n_k)
n, N

(12, 6115)

In [4]:
p_k = n_k / N
theta_hat = np.sum(k * p_k) / n
theta_hat

0.5192150449713818

In [5]:
e_k = N * binom.pmf(k, n, theta_hat)
np.round(e_k, 0)

array([1.000e+00, 1.200e+01, 7.200e+01, 2.580e+02, 6.280e+02, 1.085e+03,
       1.367e+03, 1.266e+03, 8.540e+02, 4.100e+02, 1.330e+02, 2.600e+01,
       2.000e+00])

In [6]:
r_k = (n_k - e_k) / np.sqrt(e_k)
np.round(r_k, 1)

array([ 2.1,  3.4,  3.8,  1.7,  1.7, -1.6, -0.7, -4.3, -0.9,  3.4,  4.2,
        3.7,  3. ])

In [7]:
chi_sq = np.sum(r_k**2)
np.round(chi_sq, 1)

110.5